package com.jio.ngo.exception.constant;

public class ExceptionManagementConstant
{
	public static final String securityExceptionList = 
	"SELECT APPLICATION,APPLICATIONINAPPMASTER,BUSINESSRELFORSECURITYEXCEP,BUSINESSUNIT,DAYSTOEXPIRATION,\r\n" + 
	"DESCRIPTION,DOMAIN,EXCEPTIONAGAINST,EXCEPTIONEXPIRYDATE,EXCEPTIONID,EXCEPTIONSUBCATEGORY,\r\n" + 
	"FINDING,FINDINGID,NUMBEROFEXTENSIONS,OVERALLSTATUS,PLATFORM,PLATFORMINAPPMASTER,\r\n" + 
	"POLICYSTATEMENT,POLICYSTATEMENTID,REQUESTER,REQUESTERSHOD,RISKDESCRIPTION,\r\n" + 
	"SECURITYEXCEPTIONID,SEVERITY,STATUS,SUBMISSIONDATE,\r\n" + 
	"TECHNICALLIMITATION,APPLICATIONOWNER,BUSINESSUNITOWNER,DOMAINOWNER,PLATFORMOWNER FROM TOPS_THREAT_EXCEPTION";
	
	public static final String applicationUpdateByExceptionId = "Update TOPS_THREAT_EXCEPTION set BUSINESSUNIT=?, DOMAIN=?, PLATFORMINAPPMASTER=?, APPLICATIONINAPPMASTER=? where upper(SECURITYEXCEPTIONID)=?";

	public static final String hierarchy =
	"select PLATFORMOWNER as PRODUCTIONOWNER,DOMAINOWNER,BUOWNER AS JOURNEY,APP_NAME,APPOWNER from APPLICATION_MASTER_MAPPING \r\n" + 
	"where upper(APPOWNER)=upper(?) \r\n" + 
	"and APP_NAME=? and ROWNUM<2";

}
